Customcolorschase
adafruit/Adafruit_CircuitPython_LED_Animation pull request #51
Opened 2020-06-15 16:36 UTC by cjsieh

Allow for a list of colors to be used with the Chase animation.  New animation CustomColorsChase is provided with example.  Issue#50 .

2020-06-18 22:07 UTC, kattni commented
I am working on reviewing your code. The current Pylint failure is not in your code. I am submitting a PR with the fix.

2020-06-19 01:50 UTC, FoamyGuy approved these changes
I tested these successfully with a Neopixel  Featherwing, and with a 30 pixel strip. Really neat animation, thank you for adding it @cjsieh!

2020-06-19 20:11 UTC, kattni requested changes
Hello, @cjsieh! Thanks so much for contributing this animation. I've tested it and it works successfully. There are a few changes I'd like to see before we merge it. Please see the suggestions below. **Note:** I committed a fix to a separate file that was causing Pylint to fail on a file you had not edited. The new Pylint failure is addressed in the comments below. Make sure you update your local version `sequence.py` to match the new version in the PR.

With the new example, I think it would be better to choose some other nice color combinations and include them without themed names.

Let me know if you need any assistance with any of the changes. I'm happy to  help!

2020-06-19 20:11 UTC, kattni commented on adafruit_led_animation/animation/customcolorschase.py
> +`adafruit_led_animation.animation.rainbowchase`
This needs to be updated to match the module name, e.g. `adafruit_led_animation.animation.customcolorchase`.

2020-06-19 20:11 UTC, kattni commented on adafruit_led_animation/animation/customcolorschase.py
> +Rainbow chase animation for CircuitPython helper library for LED animations.
This needs to be updated to describe the module, e.g. `Custom color chase animation for CircuitPython helper library for LED animations.`.

2020-06-19 20:11 UTC, kattni commented on adafruit_led_animation/animation/customcolorschase.py
> +class CustomColorsChase(Chase):
Class names are typically singular. Please update this to `CustomColorChase`. This will also require updating all subsequent use of the class name.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +)
We have a worldwide community and want everyone to feel welcome and included. Including this color combination under this name limits the scope of the example to the US, and could create a situation where users from elsewhere in the world, or even in the US, feel excluded. In light of the current climate, I feel it should be removed altogether.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +# St Pat Day
Associating these color combinations with holidays could be exclusionary as some do not celebrate them. The colors are fine, but please remove the holiday themed comments.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +# Christmas
Same as above, re: removing holiday themed comments.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +# Valentines Day
Same as above, re: removing holiday themed comments.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +custom_colors_chase_rg_r = CustomColorsChase(
Consider renaming this to `custom_colors_chase_rg_reversed`. It's long, but the difference between the two is clearer.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +custom_colors_chase_rainbow = CustomColorsChase(pixels, speed=0.1, size=2, spacing=3)
I would update this to `custom_color_chase_rainbow` - removing the `s` from `colors` to match the class rename. Same suggestion goes for all instances of `custom_colors` in this example.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_all_animations.py
> +custom_colors_chase = CustomColorsChase(
Call this `custom_color_chase` to match the class rename. (As well, the class name will need to be updated.)

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_all_animations.py
> +    custom_colors_chase,
Update this to match, e.g. `custom_color_chase`.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +This example displays the basic animations in sequence, at a five second interval.
This comment needs to be updated to describe the new example.

2020-06-19 20:11 UTC, kattni commented on examples/led_animation_customcolorschase.py
> +from adafruit_led_animation.color import PINK, PURPLE, GREEN, RED, WHITE, BLUE
`PURPLE` is not used. If you do not intend to use it, please remove it from the imports.

2020-06-20 02:51 UTC, cjsieh commented on adafruit_led_animation/animation/customcolorschase.py
> +`adafruit_led_animation.animation.rainbowchase`
changed

2020-06-20 02:52 UTC, cjsieh commented on adafruit_led_animation/animation/customcolorschase.py
> +Rainbow chase animation for CircuitPython helper library for LED animations.
changed

2020-06-20 02:52 UTC, cjsieh commented on adafruit_led_animation/animation/customcolorschase.py
> +class CustomColorsChase(Chase):
changed

2020-06-20 02:52 UTC, cjsieh commented on examples/led_animation_customcolorschase.py
> +)
changed

2020-06-20 02:52 UTC, cjsieh commented on examples/led_animation_customcolorschase.py
> +# St Pat Day
changed

2020-06-20 02:52 UTC, cjsieh commented on examples/led_animation_all_animations.py
> +custom_colors_chase = CustomColorsChase(
changed

2020-06-20 02:53 UTC, cjsieh commented on examples/led_animation_all_animations.py
> +    custom_colors_chase,
changed

2020-06-20 02:53 UTC, cjsieh commented on examples/led_animation_customcolorschase.py
> +from adafruit_led_animation.color import PINK, PURPLE, GREEN, RED, WHITE, BLUE
removed

2020-06-20 03:06 UTC, cjsieh commented on examples/led_animation_customcolorschase.py
> +This example displays the basic animations in sequence, at a five second interval.
fixed

2020-06-22 15:56 UTC, kattni approved these changes
Thank you for the updates!

2020-06-22 15:56 UTC, merged